# -*- coding: utf-8 -*-
"""Project5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-gkW7dNotsIFC9nbppv62EnDZ2xrYVz
"""

pip install faker

import pandas as pd
import random
from faker import Faker

fake = Faker()

num_patients = 10000

data = []

for i in range(1, num_patients + 1):
    patient = {
        "Patient_ID": f"P{i:05d}",
        "Age": random.randint(20, 80),
        "Gender": random.choice(["Male", "Female"]),
        "Blood_Pressure": random.randint(80, 180),
        "Sugar_Level": random.randint(70, 200),
        "Cholesterol": random.randint(150, 300),
        "Heart_Rate": random.randint(60, 120)
    }
    data.append(patient)

# Create DataFrame
df = pd.DataFrame(data)

# Show sample
print(df.head(10))

# Save to CSV
df.to_csv("patients_data_faker.csv", index=False)

print("Data generated using Faker and saved as patients_data_faker.csv")

print("\n--- Detailed Analysis of Key Health Metrics ---")

metrics = ['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']

for metric in metrics:
    print(f"\nAnalysis for: {metric}")
    print("---------------------------------")
    print(df[metric].describe())

    # Further analysis by Gender
    print(f"\n{metric} distribution by Gender:")
    display(df.groupby('Gender', observed=False)[metric].describe())

    # Further analysis by Risk Level
    print(f"\n{metric} distribution by Risk Level:")
    display(df.groupby('Risk_Level', observed=False)[metric].describe())

# Convert 'Gender' to categorical type for efficiency and consistency
df['Gender'] = df['Gender'].astype('category')

# Define risk thresholds
bp_high_threshold = 160
bp_medium_threshold = 130
sugar_high_threshold = 180
sugar_medium_threshold = 140
cholesterol_high_threshold = 280
cholesterol_medium_threshold = 220

def classify_risk(row):
    risk_factors = 0
    # Check Blood Pressure
    if row['Blood_Pressure'] > bp_high_threshold:
        risk_factors += 2 # High risk factor
    elif row['Blood_Pressure'] > bp_medium_threshold:
        risk_factors += 1 # Medium risk factor

    # Check Sugar Level
    if row['Sugar_Level'] > sugar_high_threshold:
        risk_factors += 2
    elif row['Sugar_Level'] > sugar_medium_threshold:
        risk_factors += 1

    # Check Cholesterol
    if row['Cholesterol'] > cholesterol_high_threshold:
        risk_factors += 2
    elif row['Cholesterol'] > cholesterol_medium_threshold:
        risk_factors += 1

    if risk_factors >= 4:
        return 'High'
    elif risk_factors >= 2:
        return 'Medium'
    else:
        return 'Low'

# Apply the classification function to create the 'Risk_Level' column
df['Risk_Level'] = df.apply(classify_risk, axis=1)

# Convert 'Risk_Level' to categorical type for efficiency
df['Risk_Level'] = df['Risk_Level'].astype('category')

print("DataFrame with Risk_Level column:")
display(df.head())